name: go-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  schedule:
  - cron: '30 5,17 * * 1'


jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.15.x', '1.x']

    steps:
      - uses: actions/checkout@v4
      - name:  Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: 'true'
          cache: 'true'

      -  run: go version
      -  run: go mod tidy
      -  run: go test -race ./...

